[package]
name = "simulate-season"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
rating-core.workspace = true

[dev-dependencies]
serde_json.workspace = true
test-support.workspace = true
